openframeworks/apothecary

.travis.yml
apothecary/apothecary
apothecary/formulas/openssl/openssl.sh
apothecary/formulas/poco/poco.sh
scripts/build.sh

Poco OpenSSL / iOS changes.

---

.travis.yml
apothecary/apothecary
apothecary/formulas/openssl/openssl.sh
apothecary/formulas/openssl/opensslconf.h
apothecary/formulas/poco/poco.sh
scripts/build.sh
scripts/ios/install.sh
scripts/linux/install.sh
scripts/tvOS/install.sh

Having multiple passes like this fixes the issue!
Could work to modulate this with string arrays, however lets see how it builds :)
@arturoc You will have to do some tar.gz magic at the end to merge the zips and save them based.
I was thinking like another matrix running on linux that literally gets the zips at 40 minutes in, and merges them. Any other ideas?

Added Passes to iOS

---

apothecary/formulas/poco/poco.sh

- Poco Update:
Release:
https://github.com/pocoproject/poco/releases/tag/poco-1.7.1-release

Poco update to the new stable 1.7.2-release (March 17th 2016).

---

apothecary/formulas/poco/poco.sh

Remove dubugging leftover

---

.travis.yml
scripts/linuxarmv6l/CROSS_BUILD_TOOLS/build_cross_gcc.sh
scripts/linuxarmv6l/install.sh
scripts/linuxarmv6l/multistrap.conf

try to compile linuxarmv6 libraries using an stretch image and gcc6

linuxarmv6: use stretch and gcc6 toolchain

---

apothecary/formulas/poco/components
apothecary/formulas/poco/poco.sh

poco: re enable json module, vs tries to link it even when it's not

---

apothecary/formulas/glfw.sh

going to use the PR to test glfw on all platforms. 
if this passes then we can merge and next nightlies should have fix for OpenGL issues on mojave

update glfw to master - fix mojave rendering issues

---

apothecary/formulas/json.sh
scripts/build.sh
scripts/emscripten/install.sh

Only a simple update for nlohmann::json to ver 3.5

Updated nlohman::json to recent version (3.5)

---

.travis.yml
apothecary/android_configure.sh
apothecary/apothecary
apothecary/formulas/FreeImage/FreeImage.sh
apothecary/formulas/assimp.sh
apothecary/formulas/boost/boost.sh
apothecary/formulas/curl/curl.sh
apothecary/formulas/freetype/freetype.sh
apothecary/formulas/glm/glm.sh
apothecary/formulas/libxml2/libxml2.sh
apothecary/formulas/opencv/opencv.sh
apothecary/formulas/openssl/Setenv-android.sh
apothecary/formulas/openssl/openssl.sh
apothecary/formulas/poco/Android
apothecary/formulas/poco/poco.sh
apothecary/formulas/tess2/tess2.sh
apothecary/formulas/uriparser/uriparser.sh

As Google will enforce the Android 64 bit support from Aug 1st, I think it is time to support arm64 and upgrade the Android platform version to 23.

Android arm 64 bit support

---

.appveyor.yml
apothecary/formulas/fmodex.sh
apothecary/formulas/glm/glm.sh
apothecary/formulas/kiss/kiss.sh
apothecary/formulas/libxml2/libxml2.sh
apothecary/formulas/svgtiny/svgtiny.sh

replace PR #123 
-  Build libraries for mingw64
-  ~~Generates MD5SUM for each generated zip file~~
- only deploy if built on openframeworks repo

MSYS2 Mingw64 support + MD5 computation for MSYS2/VS builds

---

README.md
apothecary/PROGRESS.md
apothecary/README.md

- Updates for MSYS2 ( 64bits support, progress table, codeblocks obsolescence)
- Update build status matrix

Doc update

---

apothecary/formulas/videoInput.sh

ofTheo repo is the original one and is more uptodate (fix some MSYS2 warnings)

use ofTheo repo instead of arturoc

---

scripts/linuxarmv7l/install.sh

fix junest setup and syntax (junest -u not valid anymore)

fix CI build on arm7

---

.travis.yml
apothecary/formulas/FreeImage/Makefile.osx
apothecary/formulas/_depends/pixman.sh
apothecary/formulas/assimp.sh
apothecary/formulas/boost/boost.sh
apothecary/formulas/cairo.sh
apothecary/formulas/curl/curl.sh
apothecary/formulas/freetype/freetype.sh
apothecary/formulas/glew.sh
apothecary/formulas/glfw.sh
apothecary/formulas/libpng/libpng.sh
apothecary/formulas/libusb.sh
apothecary/formulas/libxml2/libxml2.sh
apothecary/formulas/opencv/opencv.sh
apothecary/formulas/openssl/13-macos-arm.conf
apothecary/formulas/openssl/openssl.sh
apothecary/formulas/poco/poco.sh
apothecary/formulas/rtAudio/rtAudio.sh
apothecary/formulas/svgtiny/svgtiny.sh
apothecary/formulas/tess2/tess2.sh
apothecary/formulas/uri/uri.sh
apothecary/formulas/uriparser/uriparser.sh
scripts/build.sh
scripts/osx/install.sh

I think this travis.yml change allow us to test arm64 builds for macos.
If this works for GLFW I will start adding commits for the other formulas. 
🤞

testing xcode 12 / glfw build for arm64 on macos

---

.travis.yml
scripts/linuxarmv7l/install.sh

hopefully should use root / sudo for linuxarmv7 install 
closes #160

Bugfix linux armv7 closes #160

---

.appveyor.yml

hopefully this fixes mays builds failing on appveyor

use newer msys build environment by changing image to VS 2019

---

scripts/build.sh

Changes the ENV var to get just the actual branch name.  Should allow the rest of uploading to proceed.

Fix upload

---

apothecary/PROGRESS.md
apothecary/formulas/fmod.sh
scripts/calculate_formulas.sh

Keeps older fmodex.sh formula but adds and uses fmod.sh
Goes with https://github.com/openframeworks/openFrameworks/pull/6639

adding fmod script for downloading newer fmod libs.

---

apothecary/apothecary

made it 10.13 as I thought that fixed a linking issue, but don't think it was needed. 
so putting it  back to 10.9

revert back min osx to 10.9 as the rest of OF uses that.

---

scripts/build.sh
scripts/linux/install.sh

Changes for GitHub Actions meant appveyor wasn't uploading. 
This should fix appveyor uploads

Bugfix upload

---

apothecary/formulas/glm/glm.sh

As per discussion here: 
https://github.com/openframeworks/openFrameworks/issues/6496 
Hopefully removes tons of warnings on some platforms

move glm 0.9.9.6 to 0.9.9.7

---

apothecary/formulas/videoInput.sh

closes https://github.com/openframeworks/openFrameworks/issues/6671

fix videoinput warnings

---

apothecary/formulas/videoInput.sh

download wasn't using the branch name.

fix videoinput.sh to use the branch name

---

apothecary/formulas/assimp.sh
apothecary/formulas/libusb.sh
apothecary/formulas/tess2/tess2.sh

added cmake flags for min osx target to fix warnings

---

apothecary/formulas/assimp.sh
apothecary/formulas/boost/boost.sh

Fix boost link

---

apothecary/formulas/assimp.sh
apothecary/formulas/uriparser/uriparser.sh

uriparser currently erring on CI. 
Moved to GitHub release ( from official repo ).

fix link to uriparser

---

apothecary/formulas/utf8.sh

utfcpp update from v2.3.4 to v3.2.1 
Updated to github / https

utfcpp update from v2.3.4 to v3.2.1 - Updated to github / https

---

scripts/build.sh

Temp fix for zipping windows releases. 
Ref issue here: https://github.com/actions/virtual-environments/issues/905

fix broken 7z call in github virtual env

---

.github/workflows/build-msys2.yml
apothecary/formulas/fmod.sh
apothecary/formulas/glm/glm.sh
apothecary/formulas/json.sh
apothecary/formulas/pugixml.sh
apothecary/formulas/rtAudio/rtAudio.sh
apothecary/formulas/uriparser/uriparser.sh
apothecary/formulas/utf8.sh

rtaudio, glm, pugixml,uriparser, utf8, json moved from apothecary formulas to pkg-config.
Also update from pkg-config to pkgconf

Msys2: use libs from pkg-config

---

apothecary/formulas/libxml2/libxml2.sh
apothecary/formulas/svgtiny/svgtiny.sh

Bugfix svgtiny2

---

apothecary/formulas/opencv/opencv.sh

use $EMSDK for determining emsdk location.
if it is not set, attempt to source from /emsdk.
give hint on failure.

handle custom emsdk install

---

apothecary/formulas/FreeImage/FreeImage.sh

same as #255 but based on master
fix #244

Freeimage cpp11

---

apothecary/formulas/curl/curl.sh

hopefully fixes 
https://github.com/openframeworks/openFrameworks/issues/7656

fix curl for macos

---

scripts/linuxarmv6l/multistrap.conf

stretch was removed from the raspian repos - this switches armv6l to buster

Fix armv6l

---

scripts/build.sh

Compress release for bleeding edge in build.sh

---

scripts/build.sh

emscripten build workflow

---

apothecary/formulas/curl/curl.sh
apothecary/formulas/openssl/openssl.sh
apothecary/ios.toolchain.cmake
scripts/build.sh

- toolchain 
- build package settings

Bleeding macOS fixes 
