openframeworks/apothecary

- apothecary/formulas/FreeImage/FreeImage.sh
- apothecary/formulas/FreeImage/Makefile.osx
does the .a build as universal and not in two stages. 
fixes issue with linker errors on 32bit builds on OS X
> bugfix for 32bit build of FreeImage on OS X

- apothecary/formulas/glfw.sh
- apothecary/formulas/openssl/openssl.sh
use glfw from main repo instead of our own patched version + update openssl since 1.0.2g is not available any more
> update glfw and openssl

- apothecary/formulas/assimp.sh
* make sure to build 32 and 64 bit version of assimp with .dlls with
distinct names - this is necessary as otherwise the .dll for one arch
would overwrite the other when the dll is copied into the app's bin
folder.
* copy built .dlls after building them
If we don't copy the freshly built dlls, we did build everything in
vain =)
> fix vs assimp recipe

- .appveyor.yml
- apothecary/apothecary
- apothecary/formulas/_depends/zlib.sh
- apothecary/formulas/boost/boost.sh
- apothecary/formulas/curl/curl.sh
- apothecary/formulas/freetype/freetype.sh
- apothecary/formulas/libpng/libpng.sh
- apothecary/formulas/libxml2/libxml2.sh
- apothecary/formulas/opencv.sh
- apothecary/formulas/poco/buildwin.cmd
- apothecary/formulas/poco/poco.sh
- apothecary/formulas/pugixml.sh
- apothecary/formulas/rtAudio.sh
- apothecary/formulas/uriparser/uriparser.sh
- apothecary/formulas/uriparser/vs2015/uriparser.vcxproj
- apothecary/formulas/videoInput.sh
- scripts/build.sh
Updates to support visual studio 2017 compiler and toolchain to build dependencies using apothecary. The idea is to support vs2015 and vs2017 side-by side, using the variable $VS_VER to choose which version of the compiler to target. It appears that VS2015 and VS2017 are ABI compatible, so theoretically, libs compiled with the 2015 toolset should be useable with VS2017 straightaway.
VS2017 has changed some things underneath in the toolchain, mostly to be able to support multiple instances of compiler toolchains installed side-by-side, and for this reason it might be worth porting apothecary/VS to the latest (VS2017) toolchain.
This is a work in progress. 
Building libraries on a windows system is far from seamless, mainly because there are multiple unix-style environments to choose from, …
> updates for vs2017

- apothecary/formulas/tess2/tess2.patch
TESS_UNDEF was defined to 2^31-1 when it should have been 2^16-1
on the raspberry pi.  This caused some if statements such as
`      if (v->n != TESS_UNDEF)`
to not work as expected which caused a segv.
> Fixed segv on Raspberry Pi

- apothecary/formulas/libusb.sh
This replaces the #74 PR. 
It should build fine now on Windows 32bit and 64bit. 
OS X it looks like most builds are passing, but not sure why 1 of them isn't. Maybe not important?
> Feature libusb for OS X and VS

- apothecary/formulas/libusb.sh
This should force universal 64bit / 32bit libs for the libusb formula. 
Should fix the errors reported here: https://github.com/openframeworks/openFrameworks/pull/5711
> fix to force xcode to build universal libusb

- .appveyor.yml
- scripts/build.sh
to keep compile times per build under the 1h maximum, we splits vs builds into bundles, similar to how this is done with os x bundles.
> split vs builds into bundles

- apothecary/formulas/json.sh
Move to the latest version of json.  This introduces no breaking API changes that I have noted.
Also, it fixes some issues with XCode 10.2.
e.g. 
https://github.com/bakercp/ofxHTTP/issues/49
> Update json to 3.6.1.

- apothecary/apothecary
- scripts/linuxarmv6l/install.sh
- scripts/linuxarmv7l/install.sh
Modern raspberry pi, etc identify as `armv7l`.  This avoids cross-compiler installation on arm* hosts and allows apothecary to be run from arm* hosts directly, specifically useful for addons.
Fixes #99 
Part of a fix for https://github.com/bakercp/ofxDlib/issues/26
cc @neilmendoza
> Fixes apothecary support for arm* hosts.

- apothecary/formulas/opencv/opencv.sh
The issue seems to be tied to emscripten enabling pthreads by default in newer releases. 
We have pthreads disabled ( DWITH_PTHREADS_PF=OFF ) in our apothecary cmake flags but I think USE_PTHREADS=0 needs to be explicity set before building. 
This thread is helpful: 
https://github.com/opencv/opencv/issues/14691#issuecomment-509495464 
Also see this script which sets both:
https://github.com/opencv/opencv/blob/master/platforms/js/build_js.py#L178 
🤞
> longshot but hopefully fixes the emscripten issue

- apothecary/apothecary
Hi,
was getting this error as I was working the other one,
```./apothecary: line 328: shift: too many arguments```
which is probably because $OPTIND defaults to 1 without an additional argument.
Same thing can be reproduced by running a command line `apothecary update core`, making shift = 0 or error.
This takes care of that
> [change] shift arg error with bash on osx

- apothecary/formulas/openssl/openssl.sh
closes #145
should be good to merge. 
there are loads of AppVeyor errors at the moment which aren't related but last time it was tested this change just fixed the hanging prompt for patching a file which doesn't exist.
> removes the patch that hangs vs build. closes #145

- apothecary/formulas/libxml2/libxml2.sh
CI often fails because of not getting libxml2 tarball from ftp.
Switching to http may improve the situation.
> use http to retrieve libxml2 sources

- scripts/build.sh
generates libs as openframeworksLib_msys2_mingw32.zip and openframeworksLib_msys2_mingw64.zip
> MSYS2 : change lib suffix to mingwXX

- apothecary/formulas/curl/curl.sh
closes #156 
Tested with the imageLoaderWebExample no linker errors without the LDAP.framework. 
Once this is merged we'll need to do a PR to modify [this line](https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig#L57) to remove LDAP
> removed ldap dependency on private LDAP.framework. closes #156

- apothecary/formulas/curl/curl.sh
- apothecary/formulas/opencv/opencv.sh
- apothecary/formulas/pugixml.sh
Tested the libs output on the Mac Mini M1 and had a couple of linking issues. 
This should fix the remaining issues for x86_64 and arm64 for macOS
> small fixes for libaries to make compatible with M1 machines

- apothecary/formulas/curl/curl.sh
- scripts/calculate_formulas.sh
This fixes #176 and seems like a good solution as we transition to 10.15 / 10.11 and keep backwards compatible support.
> Curl macos fix legacy

- apothecary/formulas/glfw.sh
cmake uses DCMAKE_OSX_DEPLOYMENT_TARGET to set the min sdk for osx.
we weren't setting that so it was being set twice causing the CI builds to target 10.15 instead of OSX_MIN_SDK_VER
this should be the last fix needed to get macOS libs working for both older and newer mac platforms.
> bugfix for min osx sdk being set incorrectly

- scripts/build.sh
- scripts/linux/install.sh
I think this is why both PG and nightly is failing. With the switch from travis.yml the compiler default wasn't gcc-4.9 for the gcc4 option. So Poco and other libs were being linked with newer gcc.
> Explicit linux gcc4

- scripts/build.sh
- scripts/linux/install.sh
gcc4 option isn't linking with nightly builds. 
looks like the gcc version was defaulting to gcc-5 even after installing gcc-4
> try and set default gcc and g++ to 4.9 not 5

- .github/workflows/build-emscripten.yml
- apothecary/formulas/opencv/opencv.sh
sdk-incoming-64bit isn't supported anymore so emscripten now fails to link when using the nightly builds locally. 
this switches the docker image to the official one ( the other one is now deprecated )
> fix emscripten to use offical docker and move from deprecated image

- apothecary/formulas/glfw.sh
Switches glfw to their stable 3.3.3 version. 
( we were on 3.3.0 before ) 
Fixes weird permissions errors ( due to Big Sur building 3.3.0 ), that breaks drag and drop functionality on macOS.
> glfw switch to 3.3 stable

- apothecary/formulas/fmod.sh
- apothecary/formulas/kiss/kiss.sh
need to change the install_name_tool command to look in Frameworks. 
avoids the need for setting in the Xcode project. 
related PR:
https://github.com/openframeworks/openFrameworks/pull/6679
> fix fmod formula to set correct loader path for fmod

- apothecary/formulas/opencv/opencv.sh
there are some linker errors currently for opencv running on arm64 / M1 machines. 
See: https://forum.openframeworks.cc/t/of-fullscreen-causing-crash-with-validaterenderpassdescriptor/37220/3
looking at the build logs I see a lot of linker warnings when using libtool that duplicate symbols exist because we are linking all the opencv libs into a single one. 
I think/hope changing the formula to use the actual libs produced by opencv instead of a single libtool one will fix the issue.
> Fix opencv arm64

- apothecary/formulas/opencv/opencv.sh
fixes opencv linking errors on arm64 macOS machines. 
more info here: https://forum.openframeworks.cc/t/of-fullscreen-causing-crash-with-validaterenderpassdescriptor/37220/11
> Bugfix arm64 opencv

- apothecary/formulas/glfw.sh
Current GLFW master causes a memory leak on draw with arm64 on Big Sur. Tried tracking it down, but there are tons of changes. Will try and fix for 0.12.0 but reverting to 0.11.0 glfw version for now. 
Added a small fix in branch to address drag and drop on Big Sur.
> revert glfw to version for 0.11.0. 

- apothecary/formulas/rtAudio/rtAudio.sh
the current rtaudio build emmits a call to "____chkstk_darwin()". but that symbol only exists in osx 10.14+, meaning all OF apps using rtaudio crash in osx up to 10.13. 
the fix is to set the deployment target to 10.9. it supresses chkstk_darwin on intel based builds (the arm64 build is unaffected). 
happy to answer questions, hope this gets accepted quick.
> rtaudio osx: set deployment-target to osx 10.9

- .github/workflows/build-msys2.yml
Add CI build support for UCRT64 and CLANG64 environment in MSYS2. 
mingw32 flavor kept in the matrix. To be delete when 32 bits support will be officially dropped.
> CI build of additional Msys2 flavours

- apothecary/formulas/poco/poco.sh
@danoli3 this is so the CI can pass, but also you mentioned that we might not use Poco going forward for Android
> remove android from poco formula

- scripts/build.sh
inconsistency between generated zip file name and released file name
> ci(msys2): fix zip building

- apothecary/formulas/svgtiny/svgtiny.sh
Apply patch as on osx
Fix #237
> svgtiny(msys2) : fix clang64 warnings

- apothecary/formulas/svgtiny/svgtiny.sh
Turns out svgtiny wasn't being built but also wasn't erroring so it was missing from the packaged libs folder. 
This is due to the CI using newer VS compilers.
> fix broken svgtiny formula that wasn't erroring

- .github/workflows/build-msys2.yml
fix #247 
use pacboy to install gperf, libxml2, python3
> fix(svgtiny): compilation on ucrt64

- apothecary/formulas/glm/glm.sh
I've noticed GLM fixed this kind of warning, but it is not yet on any release (2020 was most recent) so I'm using latest from master 
```
In file included from /Volumes/tool/ofw/apps/WerkApps/Scenes/src/main.cpp:19:
In file included from src/ofApp.h:3:
In file included from ../../../libs/openFrameworks/ofMain.h:19:
In file included from ../../../libs/openFrameworks/utils/ofJson.h:8:
In file included from ../../../libs/openFrameworks/types/ofParameter.h:8:
In file included from ../../../libs/openFrameworks/types/ofColor.h:4:
In file included from ../../../libs/glm/include/glm/gtx/wrap.hpp:16:
In file included from ../../../libs/glm/include/glm/gtx/../glm.hpp:132:
In file included from ../../../libs/glm/include/glm/packing.hpp:173:
In file included from …
```
> GLM from master

- .github/workflows/build-vs2022_arm64.yml
- .github/workflows/build-vs2022_arm64ec.yml
- .github/workflows/build-vs2022_x64.yml
- apothecary/apothecary
- apothecary/formulas/FreeImage/FreeImage.sh
- apothecary/formulas/assimp.sh
- apothecary/formulas/fmod.sh
- apothecary/formulas/fmodex.sh
- apothecary/formulas/opencv/opencv.sh
- apothecary/formulas/pugixml.sh
- apothecary/formulas/rtAudio/rtAudio.sh
- scripts/load.sh
- scripts/save.sh
- scripts/simd.sh
- Fixed most linking CRT issue for x64. (rtAudio, assimp, opencv) = dynamic with debug/release 
- Modified Apothecary with more variables for VS building
- Added ARM64EC support + working - cmake all targets - targets Windows 11 automatically
- Global VS variables (c++ exception handler / settings) 
- Added variables to build variants for MSVC / LLVM (clang)
> Latest Libraries - VS2022 linker fixes - ARM64EC 
